### ISSUE TITLE
Tutorial crashes on user create

### ISSUE THREAD

**Issue by marcuskelly** [diamond-org/flask-diamond#17]
When I click "Create" on the user page, the app crashes. This happens on both localhost and PythonAnywhere.com

Python version
2.7 (I used Python 3.5 on PythonAnywhere, same issue)

Operating system
Ubuntu 16.04.1 LTS

The error message in the browser
UndefinedError: 'flask_admin.contrib.sqla.form.UserForm object' has no attribute 'name'

The error message that is logged on the command line
UndefinedError: 'flask_admin.contrib.sqla.form.UserForm object' has no attribute 'name'

**Comment by devalbo** [comment]
The user model flask-diamond sets up does not have a name field. When the template goes to render the model's data, it throws this error. You can prevent the error by commenting out the line `{{ lib.render_field(form, form.name) }}` in the views/administration/templates/admin/create_user.html file. Comment out lines using `{#` and `#}`.

There is a related error in the administration facet in the create_model method of the UserView class in administration.py when you try to create the actual user.

**Comment by marcuskelly** [comment]
Hi devalbo,

Thanks for your reply. I actually did the same fix myself. I just wasn't sure if this was the proper fix.

Just to confirm..
To stop app crashing I commented out line 41 in create_user.html `{{ lib.render_field(form, form.name) }}`
path planets/planets/views/administration/templates/admin/create_user.html

And line 132 in administration.py `name=form.data["name"],`
path planets/planets/lib/python3.5/site-packages/flask_diamond/facets/administration.py

**Comment by iandennismiller** [comment]
Hi @marcuskelly @devalbo - thanks for reporting this!  It's been fixed in `develop` and will be included in the next revision.
