### ISSUE TITLE
Read the Docs, System requirements, Ubuntu, no package sqlite-dev

### ISSUE THREAD

**Issue by stoneyv** [diamond-org/flask-diamond#21]
I spent a bit of time trying to figure out how the Read the Docs are generated so that I could make a PR.
The system requirements for Ubuntu list a package that does not exist.  sqlite-dev does not exist.
I used this command to search for possible packages.
apt-cache search sqlite 

This might be the correct package
sudo apt install libsqlite3-dev

**Comment by brennv** [comment]
Thanks @stoneyv Fix PR: https://github.com/diamond-org/flask-diamond/pull/28/commits/eeb751d3a946631f73086e571082325b6de43224

**Comment by iandennismiller** [comment]
@stoneyv @brennv thank you both - this change is now in the develop branch.
